### ISSUE TITLE
Potential panic in keytab/keytab.go

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [jcmturner/gokrb5#339]
On my fork, using fuzzing we're able to gain a panic with the following stacktrace:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/tyrannosaurus-becks/gokrb5/keytab.readBytes(0x4270006, 0x30, 0x35, 0xc000054cd8, 0x3030, 0xc000054d00, 0xea7c22730, 0x11bdd40, 0x0)
/Users/xntrik/go/src/github.com/tyrannosaurus-becks/gokrb5/keytab/keytab.go:347 +0x1f0
github.com/tyrannosaurus-becks/gokrb5/keytab.(*Keytab).Unmarshal(0xc000054e88, 0x4270000, 0x3b, 0x3b, 0x5dd50a76, 0xc000054ea8)
/Users/xntrik/go/src/github.com/tyrannosaurus-becks/gokrb5/keytab/keytab.go:186 +0x698
github.com/dvyukov/go-fuzz-corpus/keytab.Fuzz(0x4270000, 0x3b, 0x3b, 0x4)
/Users/xntrik/go/src/github.com/dvyukov/go-fuzz-corpus/keytab/main.go:9 +0x7b
go-fuzz-dep.Main(0xc000054f80, 0x1, 0x1)
/var/folders/4g/lw49gkrs74b1qsdf_d9zrq4h0000gn/T/go-fuzz-build361402323/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
/var/folders/4g/lw49gkrs74b1qsdf_d9zrq4h0000gn/T/go-fuzz-build361402323/gopath/src/github.com/dvyukov/go-fuzz-corpus/keytab/go.fuzz.main/main.go:15 +0x52
exit status 2
```
This corresponds with [this line](https://github.com/jcmturner/gokrb5/blob/363118e62befa8a14ff01031c025026077fe5d6d/keytab/keytab.go#L347) on the present master branch of the repo, which holds:
```
buf := bytes.NewBuffer(b[*p : *p+s])
```

I have a PR forthcoming to fix it.

**Comment by tyrannosaurus-becks** [comment]
This wasn't intended to be fixed by the merge of the linked PR, reopening. Needs a fix in this repo too.
