### ISSUE TITLE
client.TGSExchange panics in messages.authenticatorKeyUsage on cross-domain requests

### ISSUE THREAD

**Issue by jboelter** [jcmturner/gokrb5#350]
I can consistently reproduce a panic that appears related to authenticating a service in another realm. I can reproduce on both 7.3.0 and master. Examples below are from the git commit below.

````
>git show
commit 29511b62ebd0c61e15e0347ac8956c2ad054113b (HEAD)
````

This is only happening when the TGSExchange is called recursively and it appears that the `tgt` passed into `NewTGSReq` isn't correct.  This occurs when the `default_realm` in the krb conf doesn't match the destination domain that is being authenticated.

TGSExchange.go line 63
````
		tgsReq, err = messages.NewTGSReq(cl.Credentials.CName(), kdcRealm, cl.Config, tgt, sessionKey, tgsReq.ReqBody.SName, tgsReq.Renewal)
````

Sample app w/ error handling elided. The domains have been changed, but represent a real example. In this case, the `foo.example.com` SPN resides in the `ABC.SUB.EXAMPLE.COM` domain. Setting the default_realm to a valid, but different, domain triggers this panic.
````
func main() {
	cfg, err := config.NewConfigFromString(krb5conf)
	var settings = []func(*client.Settings){
		client.DisablePAFXFAST(true),
		client.Logger(log.New(os.Stdout, "logger: ", log.Lshortfile)),
	}
	cl := client.NewClientWithPassword(username, realm, password, cfg, settings...)
	r, _ := http.NewRequest("GET", "https://foo.example.com/api/v1/token", nil)
	spnegoCl := spnego.NewClient(cl, nil, "")
	resp, err := spnegoCl.Do(r)
}

var krb5conf = `
[libdefaults]
default_realm = XYZ.SUB.EXAMPLE.COM
dns_lookup_realm = true
ticket_lifetime = 24h
renew_lifetime = 7d
forwardable = true

[realms]
ABC.SUB.EXAMPLE.COM = {
	kdc = ABC.SUB.EXAMPLE.COM:111
	admin_server = abc.sub.example.com:222
	default_domain = abc.sub.example.com
}
XYZ.SUB.EXAMPLE.COM = {
	kdc = XYZ.SUB.EXAMPLE.COM:111
	admin_server = xyz.sub.example.com:222
	default_domain = xyz.sub.example.com
}
SUB.EXAMPLE.COM = {
  kdc = SUB.EXAMPLE.COM:111
  admin_server = sub.example.com:222
  default_domain = sub.example.com
}
`
````

Log + Panic output; The 'authenticatorKeyUsage is a println I added to capture the ticket being authenticated. Note the empty ticket when crashing. (Log was generated separate from the stack trace so line #s are correct)

````
logger: settings.go:67: using SPN HTTP/api.bar.example.com
logger: settings.go:67: TGT session added for ABC.SUB.EXAMPLE.COM (EndTime: 2020-01-07 13:28:00 +0000 UTC)
authenticatorKeyUsage() {NameType:2 NameString:[krbtgt ABC.SUB.EXAMPLE.COM]}
logger: settings.go:67: ticket added to cache for krbtgt/XYZ.SUB.EXAMPLE.COM (EndTime: 2020-01-07 13:28:00 +0000 UTC)
logger: settings.go:67: TGT session added for XYZ.SUB.EXAMPLE.COM (EndTime: 2020-01-07 13:28:00 +0000 UTC)
authenticatorKeyUsage() {NameType:2 NameString:[krbtgt XYZ.SUB.EXAMPLE.COM]}
logger: settings.go:67: TGT session added for ABC.SUB.EXAMPLE.COM (EndTime: 2020-01-07 13:28:00 +0000 UTC)
authenticatorKeyUsage() {NameType:0 NameString:[]}

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
gopkg.in/jcmturner/gokrb5.v7/messages.authenticatorKeyUsage(...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/messages/APReq.go:100
gopkg.in/jcmturner/gokrb5.v7/messages.encryptAuthenticator(0x5, 0x0, 0x0, 0x1, 0xc000160a70, 0x1, 0x1, 0xffffff76, 0xc0002f3740, 0x10, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/messages/APReq.go:76 +0x39b
gopkg.in/jcmturner/gokrb5.v7/messages.NewAPReq(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/messages/APReq.go:55 +0x105
gopkg.in/jcmturner/gokrb5.v7/messages.(*TGSReq).setPAData(0xc0002f7ed0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/messages/KDCReq.go:255 +0x2d3
gopkg.in/jcmturner/gokrb5.v7/messages.NewTGSReq(0xc000000001, 0xc000160a70, 0x1, 0x1, 0xc0000a8190, 0x12, 0xc0000fe000, 0x0, 0x0, 0x0, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/messages/KDCReq.go:162 +0x1d6
gopkg.in/jcmturner/gokrb5.v7/client.(*Client).TGSExchange(0xc000172cf0, 0x5, 0xc, 0xc000370ca0, 0x1, 0x1, 0xc00032b294, 0x4, 0x4, 0x20, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/client/TGSExchange.go:63 +0x938
gopkg.in/jcmturner/gokrb5.v7/client.(*Client).TGSREQGenerateAndExchange(0xc000172cf0, 0xc000000001, 0xc000324040, 0x2, 0x2, 0xc0000a8190, 0x12, 0x5, 0xc000183c00, 0x12, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/client/TGSExchange.go:17 +0x3d8
gopkg.in/jcmturner/gokrb5.v7/client.(*Client).GetServiceTicket(0xc000172cf0, 0xc0001f1700, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/client/TGSExchange.go:98 +0x2e8
gopkg.in/jcmturner/gokrb5.v7/spnego.(*SPNEGO).InitSecContext(0xc000253680, 0x0, 0x0, 0xc000253680, 0x1)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/spnego/spnego.go:52 +0x59
gopkg.in/jcmturner/gokrb5.v7/spnego.SetSPNEGOHeader(0xc000172cf0, 0xc000292000, 0xc0001f1700, 0x1d, 0x9, 0x7f70b1f23008)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/spnego/http.go:179 +0x18e
gopkg.in/jcmturner/gokrb5.v7/spnego.(*Client).Do(0xc0000c3c00, 0xc000292000, 0x0, 0x0, 0x1)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/spnego/http.go:105 +0x3a0
gopkg.in/jcmturner/gokrb5.v7/spnego.(*Client).Do(0xc0000c3c00, 0xc000130200, 0x0, 0x0, 0xc0000c3c00)
        /mnt/c/source/aggregator/vendor/gopkg.in/jcmturner/gokrb5.v7/spnego/http.go:99 +0x1a8
main.getToken()
        /mnt/c/source/aggregator/main.go:60 +0x477
main.main()
        /mnt/c/source/aggregator/main.go:31 +0x64
exit status 2
````

**Comment by jcmturner** [comment]
Hi, there was a change merged in the last few days that specifically changed the line (TGSExchange.go line 63) you think is the issue: https://github.com/jcmturner/gokrb5/pull/322

The version of this line you have quoted is the old version. Can you try updating your master branch to get these updates and see if this resolves the issue. I want to rule this out before progressing further. Thanks.

**Comment by jboelter** [comment]
That does indeed resolve the panic. Thank you.
